export const initialValuesSingleDelegate = {
	firstName: "",
	middleName: "",
	lastName: "",
	email: "",
	gender: "",
	country: "",
	phone1: "",
	phone2: "",
	age: "",
	course: "",
	college: "",
	year: "",
	prevExp: "",
	awards: "",
	committeeOne: "", // committeee one
	committeeOne_countryOne: "",
	committeeOne_countryTwo: "",
	committeeOne_countryThree: "",
	committeeTwo: "", // committee two
	committeeTwo_countryOne: "",
	committeeTwo_countryTwo: "",
	committeeTwo_countryThree: "",
	committeeThree: "", // committee three
	committeeThree_countryOne: "",
	committeeThree_countryTwo: "",
	committeeThree_countryThree: "",
	accommodation: "",
	accommodation_type: "",
}


export const initialValuesDoubleDelegate = {
	s_firstName: "",
	s_middleName: "",
	s_lastName: "",
	d_firstName: "",
	d_middleName: "",
	d_lastName: "",
	s_email: "",
	d_email: "",
	s_gender: "",
	d_gender: "",
	s_country:"",
	d_country:"",
	s_phone1: "",
	s_phone2: "",
	d_phone1: "",
	d_phone2: "",
	s_course: "",
	d_course: "",
	s_college:"",
	d_college:"",
	s_age: "",
	d_age: "",
	s_prevExp:"",
	d_prevExp:"",
	s_awards: "",
	d_awards: "",
	committeeOne: "", // committeee one
	committeeOne_countryOne: "",
	committeeOne_countryTwo: "",
	committeeOne_countryThree: "",
	committeeTwo: "", // committee two
	committeeTwo_countryOne: "",
	committeeTwo_countryTwo: "",
	committeeTwo_countryThree: "",
	committeeThree: "", // committee three
	committeeThree_countryOne: "",
	committeeThree_countryTwo: "",
	committeeThree_countryThree: "",
	accommodation: "",
	accommodation_type: "",
}

export const committees = ["DISEC", "UNHRC", "UNCSW", "WHA", "COP-28 UNFCCC", "World bank", "SC", "UNESCO", "NATO", "Ad Hoc", "ECOSOC", "UNCND", "GA6 Legal", "UNOOSA", "IP"]

export const unfccc = ["Afghanistan",
"Albania",
"Algeria",
"Andorra",
"Angola",
"Antigua and Barbuda",
"Argentina",
"Armenia",
"Australia",
"Austria",
"Azerbaijan",
"Bahamas",
"Bahrain",
"Bangladesh",
"Barbados",
"Belarus",
"Belgium",
"Belize",
"Benin",
"Bhutan",
"Bolivia (Plurinational State of)",
"Bosnia and Herzegovina",
"Botswana",
"Brazil",
"Brunei Darussalam",
"Bulgaria",
"Burkina Faso",
"Burundi",
"Cabo Verde",
"Cambodia",
"Cameroon",
"Canada",
"Central African Republic",
"Chad",
"Chile",
"China",
"Colombia",
"Comoros",
"Congo",
"Cook Islands",
"Costa Rica",
"Cote d'Ivoire",
"Croatia",
"Cuba",
"Cyprus",
"Czechia",
"Democratic People's Republic of Korea",
"Democratic Republic of the Congo",
"Denmark",
"Djibouti",
"Dominica",
"Dominican Republic",
"Ecuador",
"Egypt",
"El Salvador",
"Equatorial Guinea",
"Eritrea",
"Estonia",
"Eswatini",
"Ethiopia",
"European Union",
"Fiji",
"Finland",
"France",
"Gabon",
"Gambia",
"Georgia",
"Germany",
"Ghana",
"Greece",
"Grenada",
"Guatemala",
"Guinea",
"Guinea-Bissau",
"Guyana",
"Haiti",
"Holy See",
"Honduras",
"Hungary",
"Iceland",
"India",
"Indonesia",
"Iran (Islamic Republic of)",
"Iraq",
"Ireland",
"Israel",
"Italy",
"Jamaica",
"Japan",
"Jordan",
"Kazakhstan",
"Kenya",
"Kiribati",
"Kuwait",
"Kyrgyzstan",
"Lao People's Democratic Republic",
"Latvia",
"Lebanon",
"Lesotho",
"Liberia",
"Libya",
"Liechtenstein",
"Lithuania",
"Luxembourg",
"Madagascar",
"Malawi",
"Malaysia",
"Maldives",
"Mali",
"Malta",
"Marshall Islands",
"Mauritania",
"Mauritius",
"Mexico",
"Micronesia (Federated States of)",
"Monaco",
"Mongolia",
"Montenegro",
"Morocco",
"Mozambique",
"Myanmar",
"Namibia",
"Nauru",
"Nepal",
"Netherlands",
"New Zealand",
"Nicaragua",
"Niger",
"Nigeria",
"Niue",
"North Macedonia",
"Norway",
"Oman",
"Pakistan",
"Palau",
"Panama",
"Papua New Guinea",
"Paraguay",
"Peru",
"Philippines",
"Poland",
"Portugal",
"Qatar",
"Republic of Korea",
"Republic of Moldova",
"Romania",
"Russian Federation",
"Rwanda",
"Saint Kitts and Nevis",
"Saint Lucia",
"Saint Vincent and the Grenadines",
"Samoa",
"San Marino",
"Sao Tome and Principe",
"Saudi Arabia",
"Senegal",
"Serbia",
"Seychelles",
"Sierra Leone",
"Singapore",
"Slovakia",
"Slovenia",
"Solomon Islands",
"Somalia",
"South Africa",
"South Sudan",
"Spain",
"Sri Lanka",
"State of Palestine",
"Sudan",
"Suriname",
"Sweden",
"Switzerland",
"Syrian Arab Republic",
"Tajikistan",
"Thailand",
"Timor-Leste",
"Togo",
"Tonga",
"Trinidad and Tobago",
"Tunisia",
"T眉rkiye",
"Turkmenistan",
"Tuvalu",
"Uganda",
"Ukraine",
"United Arab Emirates",
"United Kingdom of Great Britain and Northern Ireland",
"United Republic of Tanzania",
"United States of America",
"Uruguay",
"Uzbekistan",
"Vanuatu",
"Venezuela (Bolivarian Republic of)",
"Viet Nam",
"Yemen",
"Zambia",
"Zimbabwe",
]
